package consts

const (

	// workspace component kind
	PersistentVolumeClaim = "PersistentVolumeClaim"
	SERVICE               = "SERVICE"
	CONFIGMAP             = "CONFIGMAP"

	WS_STARTING_TIMEOUT_PERIOD  = 600
	WS_RESTORING_TIMEOUT_PERIOD = 600
	WS_STOPPING_TIMEOUT_PERIOD  = 600
	WS_DELETING_TIMEOUT_PERIOD  = 600

	WS_PENDING = "PENDING"

	WS_STARTING         = "STARTING"
	WS_RESTORING        = "RESTORING"
	WS_STARTING_TIMEOUT = "STARTING_TIMEOUT"
	WS_RUNNING          = "RUNNING"

	WS_DELETING         = "DELETING"
	WS_DELETED          = "DELETED"
	WS_DELETING_TIMEOUT = "DELETING_TIMEOUT"

	WS_STOPPING         = "STOPPING"
	WS_STOPPED          = "STOPPED"
	WS_STOPPING_TIMEOUT = "STOPPING_TIMEOUT"
	WS_ERROR            = "ERROR"

	WORKSPACE_TASK_PRE_EXECUTE = "PRE_EXECUTE"
	WORKSPACE_TASK_EXECUTING   = "EXECUTING"
	WORKSPACE_TASK_SUCCESS     = "SUCCESS"
	WORKSPACE_TASK_ERROR       = "ERROR"
	WORKSPACE_TASK_TIMEOUT     = "TIMEOUT"
	WORKSPACE_TASK_FINISH      = "FINISH"
)
