package consts

const (
	WS_PENDING          = "PENDING"
	WS_STARTING         = "STARTING"
	WS_STARTING_TIMEOUT = "STARTING_TIMEOUT"
	WS_RUNNING          = "RUNNING"
	WS_DELETING         = "DELETING"
	WS_DELETING_TIMEOUT = "DELETING_TIMEOUT"
	WS_STOPPING         = "STOPPING"
	WS_STOPPING_TIMEOUT = "STOPPING_TIMEOUT"
	WS_ERROR            = "ERROR"
)
